---
title: "Predicting Breast Cancer"
author: "Francis Osei"
date: "17/12/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
```

```{r,,include=F }
library(tidyverse)
library(dplyr)
library(ggplot2)
library(GGally)
library(ggbeeswarm)
library(cowplot)
```

```{r}
data <- tibble(x= 1:100, y= 1:100)
data %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(10, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(10, 100, 10)) +
  geom_rect(xmin = 36, xmax=64, ymin=94, ymax=100, color='black',
            fill='white', size=0.25) +
  annotate('text', x= 50, y=97,label= 'Breast Cancer', size=3)+
  geom_segment(
    x=50, xend=50, y=94, yend=83.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
            fill='white', size=0.25) +
  annotate('text', x= 50, y=78,label= 'Data Analysis', size=3)+
  geom_segment(
    x=50, xend=50, y=94, yend=83.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(
    x=90, xend=90, y=65, yend=58.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed")) +
  geom_segment(
    x=50, xend=50, y=73, yend=63.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(
    x=10, xend=10, y=65, yend=58.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(
    x=35, xend=35, y=65, yend=58.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed")) +
  geom_segment(
    x=65, xend=65, y=65, yend=58.3, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed")) +
  geom_segment(
    x=10, xend=90, y=65, yend=65, 
    size=0.15, linejoin = "mitre", lineend = "butt")+
  geom_rect(xmin = 1, xmax=19, ymin=49, ymax=58, 
              color='black', fill='white', size=0.25) +
  annotate('text', x= 10, y=54, size=3,
             label= 'Heatmap \n(Correlation plot)')+
  geom_rect(xmin = 26, xmax=44, ymin=49, ymax=58, 
              color='black', fill='white', size=0.25) +
  annotate('text', x= 35, y=54, size=2.5,
             label= 'Beeswarm plot\n (quassirandom)')+
  geom_rect(xmin = 56, xmax=74, ymin=49, ymax=58, 
              color='black', fill='white', size=0.25) +
  annotate('text', x= 65, y=54, size=3,
             label= 'Histogram')+
  geom_rect(xmin = 81, xmax=99, ymin=49, ymax=58, 
              color='black', fill='white', size=0.25) +
  annotate('text', x= 90, y=54, size=3,
             label= 'Scatter plot\n with ellipses')+
  annotate('text', x= 50, y=40, size=3.5,
             label= 'Overall process flow of breast cancer data Visualisation')+
  annotate('text', x= 50, y=30, size=3,
             label= 'Source: Peter Higgins\n1/26/2019')+
  theme_void()
```


```{r,include=F}
cancer <- readr::read_csv("https://raw.githubusercontent.com/Franosei/Data-Visualization-project/main/Data/Breast%20cancer.csv")
cancer$id <- as.numeric(factor(cancer$id, 
                  levels=unique(cancer$id)))
glimpse(cancer)
```

```{r, include=F}
cancer_norm <- cancer
cancer_norm[3:32] <- scale(cancer_norm[3:32])
```

```{r}
data <- tibble(x= 1:110, y= 1:110)
data %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(10, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(10, 100, 10)) +
  geom_rect(xmin = 36, xmax=64, ymin=94, ymax=100, color='black',fill='white', size=0.25) +
  annotate('text', x= 50, y=97,label= 'Data Feature', size=3)+
  geom_segment(x=50, xend=50, y=94, yend=80,size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x=20, xend=80, y=80, yend=80, size=0.15, linejoin = "mitre", lineend = "butt")+
  geom_segment(x=20, xend=20, y=80, yend=70, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x=80, xend=80, y=80, yend=70, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 10, xmax=30, ymin=60, ymax=70, color='black',fill='white', size=0.25) +
  annotate('text', x= 20, y=65,label= 'Bening\n(B)', size=3)+
  geom_rect(xmin = 70, xmax=90, ymin=60, ymax=70, color='black',fill='white', size=0.25) +
  annotate('text', x= 80, y=65,label= 'Malingent\n(M)', size=3)+
  geom_segment(x=20, xend=20, y=60, yend=50,size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x=80, xend=80, y=60, yend=50,size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x=5, xend=100, y=50, yend=50,size=0.15, linejoin = "mitre", lineend = "butt")+
  geom_segment(x=5, xend=5, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 0, xmax=10, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 5, y=40,label= 'Radius', size=3)+
  geom_segment(x=20, xend=20, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 13, xmax=23, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 18, y=40,label= 'Texture', size=3)+
  geom_segment(x=30, xend=30, y=50, yend=35,size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 25, xmax=35, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 30, y=40,label= 'Perimeter', size=3)+
  geom_segment(x=40, xend=40, y=50, yend=35,size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 37, xmax=47, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 42, y=40,label= 'Area', size=3)+
  geom_segment(x=55, xend=55, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 49, xmax=59, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 54, y=40,label= 'Smooth.', size=3)+
  geom_segment(x=65, xend=65, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 61, xmax=71, ymin=35, ymax=45, color='black',fill='white', size=0.25) +
  annotate('text', x= 67, y=40,label= 'Compact.', size=3)+
  geom_segment(x=77, xend=77, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 73, xmax=83, ymin=35, ymax=45, color='black',fill='white', size=0.25)+
  annotate('text', x= 78, y=40,label= 'Concavity', size=3)+
  geom_segment(x=90, xend=90, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 85, xmax=95, ymin=35, ymax=45, color='black',fill='white', size=0.25)+
  annotate('text', x= 90, y=40,label= 'Convexity', size=3)+
  geom_segment(x=100, xend=100, y=50, yend=35, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type="closed"))+
  geom_rect(xmin = 97, xmax=107, ymin=35, ymax=45, color='black',fill='white', size=0.25)+
  annotate('text', x= 102, y=40,label= 'Frac. dim.', size=3)+
  geom_segment(x=0, xend=0, y=35, yend=25, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed")) +
  geom_segment(x=107, xend=107, y=35, yend=25, size=0.15, linejoin = "mitre", lineend = "butt",arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x=0, xend=107, y=25, yend=25, size=0.15, linejoin = "mitre", lineend = "butt")+
  geom_segment(x=20, xend=20, y=25, yend=20, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 15, xmax=25, ymin=10, ymax=20, color='black',fill='white', size=0.25) +
  annotate('text', x= 20, y=15,label= 'mean', size=3)+
  geom_segment(x=50, xend=50, y=25, yend=20, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 40, xmax=60, ymin=10, ymax=20, color='black',fill='white', size=0.25) +
  annotate('text', x= 50, y=15,label= 'Standard Error\n(se)', size=3)+
    geom_segment(x=80, xend=80, y=25, yend=20, size=0.15, linejoin = "mitre", lineend = "butt", arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 75, xmax=85, ymin=10, ymax=20, color='black',fill='white', size=0.25) +
  annotate('text', x= 80, y=15,label= 'worst', size=3)+
  annotate('text', x= 55, y=0, size=4,label= 'Data Representation')+
   theme_void()
  
  
  
  
```


```{r}
cancer_norm %>% 
  pivot_longer(cols = c(3:12), names_to = "variables") %>% 
  ggplot(aes(x = variables,y=value,colour = diagnosis))+
  geom_quasirandom(alpha = 1,method = "smiley")+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 45, hjust=1))+ theme(axis.title.x = element_blank())+
  labs(title = "Swarm Plot for the First Ten Nucleus features")
  #+ scale_x_discrete(label=abbreviate)
```


```{r}
cancer_norm %>% 
  pivot_longer(cols = c(13:22), names_to = "variables") %>% 
  ggplot(aes(x = variables,y=value,colour = diagnosis))+
  geom_quasirandom(alpha = 1,method = "smiley")+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 45, hjust=1))+ theme(axis.title.x = element_blank())+
  labs(title = "Swarm Plot for the Middle Ten Nucleus features")
```



```{r}
cancer_norm %>% 
  pivot_longer(cols = c(23:32), names_to = "variables") %>% 
  ggplot(aes(x = variables,y=value,colour = diagnosis))+
  geom_quasirandom(alpha = 1,method = "smiley")+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 45, hjust=1))+ theme(axis.title.x = element_blank())+
  labs(title = "Swarm Plot for the Last Ten Nucleus features")

```

Some plots shows clear differentiation between the Malignant and Bening cell whiles others are very difficult to distinguish. We tried to use different plot to see if we can get a clear picture of the the difference between Bening and Malignant.
```{r}
data_long <- cancer %>% 
  pivot_longer(cols = contains(c("smoothness","symmetry","fractal","concavity")), names_to = "variables") 
data_long %>% 
  ggplot(aes(y=value,fill = diagnosis))+
  geom_histogram(alpha = 4,bins = 20,position = "identity")+
  facet_wrap(~variables, scale = "free", ncol = 4)+
  coord_flip()+
  theme(axis.title.x = element_blank())+
  labs(title = "Difficult  Nucleus features to Differentiate among Diagnosis")
```


```{r}
#library(ggforce)
#cancer %>%
  #ggplot(aes(x=symmetry_mean,y = radius_mean))+
  #geom_mark_ellipse(aes(fill = diagnosis,
                        #label = diagnosis),
                    #expand = unit(0.5,"mm"),
                    #label.buffer = unit(-5,"mm"))+
  #geom_point(aes(color = diagnosis))+
  #theme(legend.position = "none")
```


```{r}
p1 <- cancer %>% 
  ggplot(aes(x=symmetry_mean,y = radius_mean,colour = diagnosis)) +
  geom_point(size = 3) +
  stat_ellipse(aes(fill = diagnosis), geom="polygon",level=0.95,alpha=0.4,type = "norm") +
  guides(colour = "legend")
p2 <- cancer %>% 
  ggplot(aes(x=smoothness_mean,y = radius_mean,colour = diagnosis)) +
  geom_point(size = 3) +
  stat_ellipse(aes(fill = diagnosis), geom="polygon",level=0.95,alpha=0.4,type = "norm") +
  guides(colour = "legend")
p3 <- cancer %>% 
  ggplot(aes(x=concavity_mean,y = radius_mean,colour = diagnosis)) +
  geom_point(size = 3) +
  stat_ellipse(aes(fill = diagnosis), geom="polygon",level=0.95,alpha=0.4,type = "norm") +
  guides(colour = "legend")
p4 <- cancer %>% 
  ggplot(aes(x=fractal_dimension_mean,y = radius_mean,colour = diagnosis)) +
  geom_point(size = 3) +
  stat_ellipse(aes(fill = diagnosis), geom="polygon",level=0.95,alpha=0.4,type = "norm") +
  guides(colour = "legend")
```

```{r}
combined_plot <- plot_grid(p1 + theme(legend.position = "none"), 
          p2 + theme(legend.position = "none"),p3 + theme(legend.position = "none"),p4 + theme(legend.position = "none"),
          labels = c('A', 'B','C','D'), label_size = 12)
legend <- get_legend(p2 + guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom"))
plot_row <- plot_grid(combined_plot, legend, ncol = 1, rel_heights = c(1, .1))
plot_row
```

```{r}


```

